server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 837769723
    url: jdbc:mysql://localhost/sr?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true