server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 837769723
    url: jdbc:mysql://localhost/sr?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: TNgmEswfjwYTaaU0G8pTz9fbFlt5wfxx
    database: 2
  session:
    store-type: redis